"""empty message

Revision ID: 1f57888fa7ed
Revises:
Create Date: 2020-02-08 23:43:37.967687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f57888fa7ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('favicon', sa.String(length=1), nullable=True))
    op.add_column('goals', sa.Column('image_location', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'image_location')
    op.drop_column('goals', 'favicon')
    # ### end Alembic commands ###
